# Generated by Django 5.2.3 on 2025-06-17 12:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=13)),
                ('name', models.CharField(max_length=255)),
                ('credits', models.PositiveIntegerField()),
                ('myiuca_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Versions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('FALL', 'Fall'), ('SPRING', 'Spring')], max_length=6)),
                ('academic_year', models.CharField(max_length=9)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.catalog')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lecturer')),
            ],
        ),
        migrations.CreateModel(
            name='Course_Videos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('album_link_id', models.IntegerField()),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course_versions')),
            ],
        ),
    ]
