# Generated by Django 5.2.3 on 2025-06-23 13:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_versions',
            name='lecturer',
        ),
        migrations.AlterField(
            model_name='catalog',
            name='credits',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='myiuca_id',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='course_versions',
            name='academic_year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='course_versions',
            name='semester',
            field=models.CharField(choices=[('Fall', 'fall'), ('Spring', 'spring')], max_length=6),
        ),
        migrations.CreateModel(
            name='Course_Lecture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('album_link_id', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course_versions')),
            ],
        ),
        migrations.DeleteModel(
            name='Course_Videos',
        ),
        migrations.DeleteModel(
            name='Lecturer',
        ),
    ]
