# Generated by Codex for the lectureLib MVP.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_course_versions_lecturer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=180, verbose_name="Название")),
                ("code", models.CharField(blank=True, max_length=32, verbose_name="Код курса")),
                ("summary", models.CharField(blank=True, max_length=260, verbose_name="Краткое описание")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("instructor", models.CharField(blank=True, max_length=120, verbose_name="Преподаватель")),
                ("cover_url", models.URLField(blank=True, verbose_name="Обложка")),
                ("is_published", models.BooleanField(default=True, verbose_name="Опубликован")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлен")),
            ],
            options={
                "verbose_name": "курс",
                "verbose_name_plural": "курсы",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=180, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "bunny_embed_url",
                    models.URLField(
                        help_text="Например: https://iframe.mediadelivery.net/embed/...",
                        verbose_name="Bunny embed URL",
                    ),
                ),
                ("duration_label", models.CharField(blank=True, max_length=32, verbose_name="Длительность")),
                ("position", models.PositiveIntegerField(default=1, verbose_name="Порядок")),
                ("is_published", models.BooleanField(default=True, verbose_name="Опубликовано")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="main.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "видео",
                "verbose_name_plural": "видео",
                "ordering": ["position", "id"],
            },
        ),
        migrations.DeleteModel(
            name="Course_Lecture",
        ),
        migrations.DeleteModel(
            name="Course_Versions",
        ),
        migrations.DeleteModel(
            name="Catalog",
        ),
    ]
